export enum EnvVariables {
  TOKEN_KEY = 'TOKEN_SECRET_KEY',
  TOKEN_ALGORITHM = 'TOKEN_ALGORITHM',
  API_KEY = 'EXCHANGE_RATE_API_KEY',
  GATEWAY_URL = 'GATEWAY_URL',
  INTERNAL_WEBHOOk_URL = 'INTERNAL_WEBHOOk_URL',
}
